name: todo_app project test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker-Compose
      run: docker compose up -d
    - name: Run Tests and flake
      run: docker exec backend sh -c "flake8 && pytest ."
