name: todo_app project test and deploy

on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    name: Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker-Compose
      run: docker compose up -d
    - name: Run Tests and flake
      run: docker exec backend sh -c "flake8 && pytest ."

  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    name: Deploy
    needs: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Connect and Execute Commands
      uses: appleboy/ssh-action@master
      with:
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        host: ${{secrets.HOST}}
        port: ${{secrets.PORT}}
        script: |
          cd ${{secrets.PROJECT_PATH}}
          docker-compose -f docker-compose-stage.yml stop
          git pull origin staging
          docker-compose -f docker-compose-stage.yml restart
